#ifndef __DEFAULTMAP_H__
#define __DEFAULTMAP_H__

#include <vector>
#include "charactersMapping.h"

// CM::EmptyTile is ' '
// CM::HorizontalWall is -
// CM::VerticalWall is |
// CM::Door is +
// CM::Bridge is #
// CM::ActiveTile is .

std::vector<CM> defaultMap = \
{ CM::VerticalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, 
 CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, 
 CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::VerticalWall, CM::VerticalWall, 
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, 
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::VerticalWall, CM::EmptyTile, \
 CM::VerticalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, \
 CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, \
 CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, \
 CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::VerticalWall, CM::EmptyTile, CM::VerticalWall, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::VerticalWall, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::Door, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Door, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::HorizontalWall, \
 CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::VerticalWall, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::HorizontalWall, CM::HorizontalWall, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::VerticalWall, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::HorizontalWall, CM::HorizontalWall, CM::VerticalWall, CM::EmptyTile, CM::VerticalWall, CM::VerticalWall, CM::EmptyTile, CM::VerticalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, \
 CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::Door, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, \
 CM::HorizontalWall, CM::HorizontalWall, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::Door, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, \
 CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::EmptyTile, CM::VerticalWall, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::EmptyTile, CM::VerticalWall, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, \
 CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::Door, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, \
 CM::HorizontalWall, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::EmptyTile, CM::VerticalWall, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, \
 CM::EmptyTile, CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::EmptyTile, CM::VerticalWall, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, \
 CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, \
 CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Door, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::EmptyTile, CM::VerticalWall, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, \
 CM::EmptyTile, CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::Bridge, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::EmptyTile, \
 CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::EmptyTile, CM::VerticalWall, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, \
 CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::EmptyTile, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::Door, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, \
 CM::EmptyTile, CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::Door, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, \
 CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::VerticalWall, CM::EmptyTile, CM::VerticalWall, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::Door, \
 CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::EmptyTile, CM::EmptyTile, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, \
 CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::Bridge, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::Door, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, \
 CM::HorizontalWall, CM::VerticalWall, CM::EmptyTile, CM::VerticalWall, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, \
 CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::EmptyTile, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::VerticalWall, CM::EmptyTile, CM::VerticalWall, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, \
 CM::EmptyTile, CM::VerticalWall, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::HorizontalWall, \
 CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::Door, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, \
 CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::EmptyTile, \
 CM::VerticalWall, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::Bridge, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::EmptyTile, CM::VerticalWall, \
 CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::Door, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Bridge, CM::Door, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::EmptyTile, CM::VerticalWall, CM::VerticalWall, \
 CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, \
 CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::ActiveTile, CM::VerticalWall, CM::EmptyTile, CM::VerticalWall, CM::VerticalWall, CM::EmptyTile, \
 CM::EmptyTile, CM::VerticalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, \
 CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, \
 CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, \
 CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::VerticalWall, CM::EmptyTile, CM::VerticalWall, CM::VerticalWall, CM::EmptyTile, CM::EmptyTile, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, \
 CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::EmptyTile, CM::VerticalWall, CM::VerticalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, \
 CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, \
 CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, \
 CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, \
 CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::HorizontalWall, CM::VerticalWall};

#endif
